package foodordering;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 2ndyrGroupB
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        addbtn.setEnabled(false);
        loadrecord(jTable1);
        paybtn.setEnabled(false);
        idtxt.setVisible(false);
        removebtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addbtn = new javax.swing.JButton();
        paybtn = new javax.swing.JButton();
        removebtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        producttxt = new javax.swing.JLabel();
        pricetxt = new javax.swing.JLabel();
        qtytxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        idtxt = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sumtxt = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        customertxt = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 89, 380, 200));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 89, 385, 200));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FOODS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CART");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, -1));

        addbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addbtn.setText("ADD TO CART");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        getContentPane().add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        paybtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        paybtn.setText("PAY");
        paybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paybtnActionPerformed(evt);
            }
        });
        getContentPane().add(paybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, -1, -1));

        removebtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        removebtn.setText("REMOVE");
        removebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removebtnActionPerformed(evt);
            }
        });
        getContentPane().add(removebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, -1, -1));

        backbtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        backbtn.setText("Logout");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Price :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Quantity :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        producttxt.setBackground(new java.awt.Color(255, 255, 255));
        producttxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        producttxt.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(producttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 80, 20));

        pricetxt.setBackground(new java.awt.Color(255, 255, 255));
        pricetxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pricetxt.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(pricetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 60, 20));

        qtytxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        qtytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtytxtActionPerformed(evt);
            }
        });
        getContentPane().add(qtytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 361, 92, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Product :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        idtxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(idtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 50, 20));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sub Total :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, -1, -1));

        sumtxt.setBackground(new java.awt.Color(255, 255, 255));
        sumtxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sumtxt.setForeground(new java.awt.Color(255, 255, 255));
        sumtxt.setText("0");
        getContentPane().add(sumtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 51, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Customer :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, -1, -1));

        customertxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        customertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customertxtActionPerformed(evt);
            }
        });
        getContentPane().add(customertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 112, 30));

        jPanel1.setBackground(new java.awt.Color(255, 103, 31));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 80));

        jPanel2.setBackground(new java.awt.Color(24, 41, 81));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 810, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void loadrecord(JTable table) {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/store", "root", "");
            PreparedStatement ps = con.prepareStatement("SELECT * FROM product");
            ResultSet rs = ps.executeQuery();
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.setRowCount(0);
            Object[] row;
            while (rs.next()) {
                row = new Object[3];
                row[0] = rs.getInt(1);
                row[1] = rs.getString(2);
                row[2] = rs.getInt(3);
                model.addRow(row);
            }
            con.close();
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }

    public void loadrecord1(JTable table) {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/store", "root", "");
            PreparedStatement ps = con.prepareStatement("SELECT * FROM cart");
            ResultSet rs = ps.executeQuery();
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.setRowCount(0);
            Object[] row;
            while (rs.next()) {
                row = new Object[4];
                row[0] = rs.getInt(1);
                row[1] = rs.getString(2);
                row[2] = rs.getString(3);
                row[3] = rs.getInt(4);
                model.addRow(row);
            }
            con.close();
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        String id = idtxt.getText();
        String product = producttxt.getText();
        String price = pricetxt.getText();

        int prices = Integer.parseInt(price);
        int qty = Integer.parseInt(qtytxt.getText());
        int total = prices * qty;
        String tot = String.valueOf(total);
        String Quantity = String.valueOf(qty);

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/store", "root", "");

            PreparedStatement ps = con.prepareStatement("INSERT INTO cart (id, product, quantity, price) values (?,?,?,?)");
            ps.setString(1, id);
            ps.setString(2, product);
            ps.setString(3, Quantity);
            ps.setString(4, tot);
            ps.execute();
            con.close();
            loadrecord(jTable1);
            idtxt.setText("0");
            producttxt.setText("");
            pricetxt.setText("");
            qtytxt.setText("");
            loadrecord1(jTable2);
            int sum = Integer.parseInt(sumtxt.getText());
            int over = sum + total;
            String t = String.valueOf(over);
            sumtxt.setText(t);
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
        paybtn.setEnabled(true);
        addbtn.setEnabled(false);
    }//GEN-LAST:event_addbtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        addbtn.setEnabled(true);
        int rowIndex = jTable1.getSelectedRow();
        idtxt.setText(jTable1.getValueAt(rowIndex, 0).toString());
        producttxt.setText(jTable1.getValueAt(rowIndex, 1).toString());
        pricetxt.setText(jTable1.getValueAt(rowIndex, 2).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void paybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paybtnActionPerformed
        String customer = customertxt.getText();
        try {
            if (customer.equals("")) {
                JOptionPane.showMessageDialog(null, "Please Input Customer Field!");
            } else {
                int data = Integer.parseInt(sumtxt.getText());
                Payment p = new Payment(data);
                p.setVisible(true);
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/store", "root", "");

                java.sql.Statement stmt = con.createStatement();
                String query = "INSERT INTO `sales` (`customer`, `total`) VALUES('" + customer + "', '" + data + "')";
                stmt.execute(query);

                PreparedStatement ps = con.prepareStatement("DELETE FROM cart");
                ps.execute();
                con.close();
                loadrecord1(jTable2);
//                sumtxt.setText("");
            }
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
        customertxt.setText("");

    }//GEN-LAST:event_paybtnActionPerformed

    private void removebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removebtnActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/store", "root", "");

            int i = Integer.parseInt(sumtxt.getText());
            int ii = Integer.parseInt(pricetxt.getText());
            int t = i - ii;
            String f = String.valueOf(t);
            sumtxt.setText(f);

            String id = idtxt.getText();

            if (id.equals(0)) {
                JOptionPane.showMessageDialog(null, "No Data Selected!");
            } else {
                PreparedStatement ps = con.prepareStatement("DELETE FROM cart where id = '" + id + "'");
                ps.execute();
                loadrecord1(jTable2);
                con.close();
                idtxt.setText("0");
                producttxt.setText("");
                pricetxt.setText("");
            }

        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
        removebtn.setEnabled(false);
    }//GEN-LAST:event_removebtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        removebtn.setEnabled(true);
        int rowIndex = jTable2.getSelectedRow();
        idtxt.setText(jTable2.getValueAt(rowIndex, 0).toString());
        producttxt.setText(jTable2.getValueAt(rowIndex, 1).toString());
        pricetxt.setText(jTable2.getValueAt(rowIndex, 3).toString());
    }//GEN-LAST:event_jTable2MouseClicked

    private void customertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customertxtActionPerformed

    private void qtytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtytxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField customertxt;
    private javax.swing.JLabel idtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton paybtn;
    private javax.swing.JLabel pricetxt;
    private javax.swing.JLabel producttxt;
    private javax.swing.JTextField qtytxt;
    private javax.swing.JButton removebtn;
    private javax.swing.JLabel sumtxt;
    // End of variables declaration//GEN-END:variables
}
