
package foodordering;

import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author 2ndyrGroupB
 */
public class Payment extends javax.swing.JFrame {
    int cash;
    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();   
        
    }

    public Payment(int data){
        initComponents();
        String text = Integer.toString(data);
        subtotaltxt.setText(text);
        calculate();
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cashtxt = new javax.swing.JTextField();
        changetxt = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        subtotaltxt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        totaltxt = new javax.swing.JLabel();
        taxtxt = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(404, 335));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cashtxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cashtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashtxtActionPerformed(evt);
            }
        });
        cashtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cashtxtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cashtxtKeyTyped(evt);
            }
        });
        getContentPane().add(cashtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 120, -1));

        changetxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        changetxt.setText("0");
        getContentPane().add(changetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 50, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Cash :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Change :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 30));

        subtotaltxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        subtotaltxt.setText("0");
        getContentPane().add(subtotaltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 50, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Total :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        totaltxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totaltxt.setText("0");
        getContentPane().add(totaltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 40, -1));

        taxtxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        taxtxt.setText("0");
        getContentPane().add(taxtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 30, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Tax :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Sub Total :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        jPanel1.setBackground(new java.awt.Color(52, 152, 219));
        jPanel1.setForeground(new java.awt.Color(52, 152, 219));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PAYMENT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel1)
                .addContainerGap(235, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 90));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\2ndyrGroupC\\Desktop\\projects\\payment.png")); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 210, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void calculate(){
        int subtot = Integer.parseInt(subtotaltxt.getText());
        int tax = 4;
        int itax = (subtot * tax) / 100;
        int total = subtot + itax;
        totaltxt.setText(Integer.toString(total));
        taxtxt.setText(Integer.toString(itax));
    }
    private void cashtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cashtxtKeyPressed
        cash = Integer.parseInt(cashtxt.getText());
        int total = Integer.parseInt(totaltxt.getText());
        int change;
        try{
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(cash < total){
                JOptionPane.showMessageDialog(this, "insufficient");
            }else{
                change = cash - total;
                changetxt.setText(Integer.toString(change));
                }
            }
        }catch(Exception e){
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_cashtxtKeyPressed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        subtotaltxt.setText("");
        totaltxt.setText("");
        taxtxt.setText("");
        JOptionPane.showMessageDialog(null, "PAID!");
        dispose();
        
    }//GEN-LAST:event_jLabel6MouseClicked

    private void cashtxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cashtxtKeyTyped
        char isNumber = evt.getKeyChar();
        if(!(Character.isDigit(isNumber))
           || (isNumber == java.awt.event.KeyEvent.VK_BACK_SPACE)
           || (isNumber == java.awt.event.KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_cashtxtKeyTyped

    private void cashtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashtxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cashtxt;
    private javax.swing.JLabel changetxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel subtotaltxt;
    private javax.swing.JLabel taxtxt;
    private javax.swing.JLabel totaltxt;
    // End of variables declaration//GEN-END:variables

}
